name: Deploy

on:
  push:
    branches: [main, dev]
    paths:
      - "src/**"
      - ".github/**"
      - "docker-compose.prod.yaml"
      - "Dockerfile"
      - "pom.xml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: taehuyn
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: taehuyn/gms-backend:latest, taehuyn/gms-backend:${{ github.sha }}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p ~/gms-backend
            cd ~/gms-backend

            echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" > .env
            echo "JWT_ACCESS_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }}" >> .env
            echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
            echo "JWT_REFRESH_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }}" >> .env
            echo "" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE_NAME=${{ secrets.DB_DATABASE_NAME }}" >> .env
            echo "" >> .env
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
            echo "" >> .env
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
            echo "" >> .env
            echo "PAYOS_API_KEY=${{ secrets.PAYOS_API_KEY }}" >> .env
            echo "PAYOS_CHECKSUM_KEY=${{ secrets.PAYOS_CHECKSUM_KEY }}" >> .env
            echo "PAYOS_CLIENT_ID=${{ secrets.PAYOS_CLIENT_ID }}" >> .env

            docker compose -f docker-compose.prod.yaml pull

            docker compose -f docker-compose.prod.yaml up -d

            docker image prune -f
